print(1 > 2)  # False
print(1 < 2)  # True
print(1 >= 2)  # False
print(1 <= 2)  # True
print(2 >= 2)  # True
print(4 == 4)  # True
print(4 == 5)  # False
print(3 == "3")  # False
print(4 != 4)  # False
print(4 != "4")  # True
